### ISSUE TITLE
Cannot find module 'chokidar'

### ISSUE THREAD

**Issue by CJICantLie** [VultureZZ/nzbFamilyHub#4]
I get the following error when attempting "npm start", while following the readme directions.  

> nzbFamillyHub@0.1.1 start c:\nzbFamilyHub
> node app.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'chokidar'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\nzbFamilyHub\lib\fileSync.js:8:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! nzbFamillyHub@0.1.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nzbFamillyHub@0.1.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the nzbFamillyHub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nzbFamillyHub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\nzbFamilyHub\npm-debug.log

**Comment by CJICantLie** [comment]
I installed Chokidar package myself, and all seems to working now.

https://github.com/paulmillr/chokidar
