### ISSUE TITLE
Ubuntu 14.04 - Error on Start

### ISSUE THREAD

**Issue by 0mni** [VultureZZ/nzbFamilyHub#5]
Getting the following errors when started, seems okay, but logging in causes the error and crash.

```
root@danlee-server:/home/plex/nzbFamilyHub# npm start

> nzbFamillyHub@0.1.1 start /home/plex/nzbFamilyHub
> node app.js

express deprecated app.configure: Check app.get('env') in an if statement app.js:17:5
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules/connect/lib/middleware/multipart.js:86:15
connect deprecated methodOverride: use method-override npm module instead app.js:24:19
express deprecated app.configure: Check app.get('env') in an if statement app.js:30:5
WARNING: No admin login and password set in config.js defaulting to admin/password
HTTP server listening on port 3000
Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period).
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).
undefined:1



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/plex/nzbFamilyHub/lib/apiCP.js:31:30)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)

npm ERR! Linux 3.19.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! nzbFamillyHub@0.1.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nzbFamillyHub@0.1.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nzbFamillyHub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nzbFamillyHub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/plex/nzbFamilyHub/npm-debug.log
root@danlee-server:/home/plex/nzbFamilyHub# cat /home/plex/nzbFamilyHub/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle nzbFamillyHub@0.1.1~prestart: nzbFamillyHub@0.1.1
6 silly lifecycle nzbFamillyHub@0.1.1~prestart: no script for prestart, continuing
7 info lifecycle nzbFamillyHub@0.1.1~start: nzbFamillyHub@0.1.1
8 verbose lifecycle nzbFamillyHub@0.1.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle nzbFamillyHub@0.1.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/plex/nzbFamilyHub/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle nzbFamillyHub@0.1.1~start: CWD: /home/plex/nzbFamilyHub
11 silly lifecycle nzbFamillyHub@0.1.1~start: Args: [ '-c', 'node app.js' ]
12 silly lifecycle nzbFamillyHub@0.1.1~start: Returned: code: 1  signal: null
13 info lifecycle nzbFamillyHub@0.1.1~start: Failed to exec start script
14 verbose stack Error: nzbFamillyHub@0.1.1 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid nzbFamillyHub@0.1.1
16 verbose cwd /home/plex/nzbFamilyHub
17 error Linux 3.19.0-42-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error nzbFamillyHub@0.1.1 start: `node app.js`
22 error Exit status 1
23 error Failed at the nzbFamillyHub@0.1.1 start script 'node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the nzbFamillyHub package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js
23 error You can get their info via:
23 error     npm owner ls nzbFamillyHub
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by VultureZZ** [comment]
0mni, it appears you have CouchPotato enabled. Can you try disabling in the config and see if it loads the web interface for you? Also, this error happens after you attempt to login, correct?

If it works after disabling CP, re-enable it, and check your settings, something is likely incorrect with the API key or address/port.
